#pragma once

namespace PVZLevel
{

	enum PVZLevel
	{
		Adventure,
		Survival_Day,
		Survival_Night,
		Survival_Pool,
		Survival_Fog,
		Survival_Roof,
		Survival_Day_Hard,
		Survival_Night_Hard,
		Survival_Pool_Hard,
		Survival_Fog_Hard,
		Survival_Roof_Hard,
		Survival_Day_Endless,
		Survival_Night_Endless,
		Survival_Pool_Endless,
		Survival_Fog_Endless,
		Survival_Roof_Endless,
		ZomBotany,
		Wallnut_Bowling,
		Slot_Machine,
		It_s_RainingSeeds,
		Beghouled,
		Invisighoul,
		Seeing_Stars,
		Zombiguarium,
		Beghouled_Twist,
		Big_Trouble_Little_Zombie,
		Portal_Combat,
		Colum_Like_You_See_Em,
		Bobsied_Bonanza,
		Zombie_Nimble_Zombie_Quick,
		Wharka_Zombie,
		Last_Stand,
		Zombotany2,
		Wallnut_Bowling2,
		Pogo_Party,
		Dr_Zomboss_s_Revenge,
		Art_Challenge_Wallnut,
		Sunny_Day,
		Unsodded,
		Big_Time,
		Art_Challenge_Sunflower,
		Air_Raid,
		Ice_Level,
		Zen_Garden,
		High_Gravity,
		Grave_Danger,
		Can_You_DigIt,
		Dark_Stormy_Night,
		Bungee_Blitz,
		Squirrel,
		Treeof_Wisdom,
		Vasebreaker,
		To_the_Left,
		Third_Vase,
		Chain_Rection,
		Mis_forM_etal,
		Scary_Potter,
		Hokey_Pokey,
		Another_Chain_Rection,
		Aceof_Vace,
		Vasebreaker_Endless,
		I_Zombie,
		I_ZombieToo,
		IZ_CanYouDigIt,
		Totally_Nuts,
		Dead_Zeppelin,
		Me_Smash,
		Zom_Boogie,
		Three_Hit_Wonder,
		All_your_brain_z_r_belong_to_us,
		I_Zombie_Endless,
		Upsell,
		Intro,
	};

	extern const char* ToString(PVZLevel pvzl);

}

